### ISSUE TITLE
Is this SDK still considered "under development"?

### ISSUE THREAD

**Issue by Rabuske** [acrolinx/sdk-js#2]
Hello,

I'm researching what the best way to call Acrolinx API programmaticaly in a NodeJS application. I can see that this is the purpose of this library. However, when checking the documentation (https://docs.acrolinx.com/customintegrations/api-sdks-and-samples) it says that the javascript version is "in development". 

My question is: can we use this library as we would use the other version (e.g. Java, .NET, etc), or do you foresee major breaking changes and we would be better off calling the API directly or using something like the CLI client?

Thank you!
Felipe.

**Comment by acrork** [comment]
Hi Felipe,

Thanks for highlighting. The JS SDK is ready to use. We’ll update https://docs.acrolinx.com/customintegrations/api-sdks-and-samples accordingly ASAP. In most cases we recommend using one of our SDKs instead of using the API directly.

Have you had a look at https://docs.acrolinx.com/customintegrations/steps-for-building-an-integration?

We’re happy to guide you through the process of building an Acrolinx Integration. Did you already reached out to the Acrolinx SDK support? https://github.com/acrolinx/acrolinx-coding-guidance/blob/master/topics/sdk-support.md#first-contact

Best, Ralf
